### ISSUE TITLE
Angular routes can conflict with getAppWebUrl()  

### ISSUE THREAD

**Issue by mhomol** [ShareCoffee/ShareCoffee#43]
This may be more of a question than an actual issue, but I have a Provider-Hosted app and the main page uses routing with angular, so even by default, my querystring has #/ appended to it.  This is getting pulled from getAppWebUrl() during my setup of RequestExecutor, using the CrossDomain class in ShareCoffee.  Thus, the following call fails:
var executor = new SP.RequestExecutor(ShareCoffee.Commons.getAppWebUrl());

because a #/ exists along the right-hand side, so SP.RequestExecutor throws the following error:
Uncaught Error: Invalid field or parameter url.

Perhaps there is something I'm missing in the library that would help with this?

**Comment by mhomol** [comment]
for the sake of time, here's what I did locally just to get things going.  I edited the javascript file directly - the getQueryStringParameter function and look specifically for the existance of "#/" in the spliced querystring value.  Let me know your thoughts on this.

_Class.getQueryStringParameter = function(parameterName) {
      var p, parameterValue, params, _ref;
      params = document.URL.split("?")[1].split("&");
      parameterValue = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = params.length; _i < _len; _i++) {
          p = params[_i];
          if (p.split("=")[0] === parameterName) {
              if (p.split("=")[1].indexOf("#/") > 1) {
                  _results.push(p.split("=")[1].split("#/")[0]);
              } else {
                  _results.push(p.split("=")[1]);
              }
          }
        }
        return _results;
      })();
      return (_ref = parameterValue[0]) != null ? _ref : '';
    };

**Comment by ThorstenHans** [comment]
Thanks for the advice, haven't used it in combination with Provider-Hosted Angular App. Will double check it the upcoming week and provide a bugfix asap.

Thanks again

**Comment by ThorstenHans** [comment]
See Issue #44
