### ISSUE TITLE
.for IE8 issue

### ISSUE THREAD

**Issue by debajyotimahanta** [ShareCoffee/ShareCoffee#45]
.for doesnt work in IE 8, if i changed to something like  .fore it works. is this a know bug. Does it support ie8?

**Comment by ThorstenHans** [comment]
Hmm, it's targeting #SharePoint and #Office365 don't actually know about #SP2013 SP1 but Office365 requires #IE9

**Comment by ThorstenHans** [comment]
okay SP2013 supports IE8, I'll fix it during the week
