### ISSUE TITLE
IE8 issues of ShareCoffee

### ISSUE THREAD

**Issue by manu-khullar** [ShareCoffee/ShareCoffee#46]
Please change the sharecoffee.js not to include keywords like for and delete in the below section

create: {
        "for": new ShareCoffee.CrossDomainRESTFactory('POST')
      },
      read: {
        "for": new ShareCoffee.CrossDomainRESTFactory('GET')
      },
      update: {
        "for": new ShareCoffee.CrossDomainRESTFactory('POST', true)
      },
      "delete": {
        "for": new ShareCoffee.CrossDomainRESTFactory('DELETE')
      }

If I use below it works in IE 8 as well completely.
create: {
        "fore": new ShareCoffee.CrossDomainRESTFactory('POST')
      },
      read: {
        "fore": new ShareCoffee.CrossDomainRESTFactory('GET')
      },
      update: {
        "fore": new ShareCoffee.CrossDomainRESTFactory('POST', true)
      },
      "deleted": {
        "fore": new ShareCoffee.CrossDomainRESTFactory('DELETE')
      }

**Comment by ThorstenHans** [comment]
Hmm, it's targeting #SharePoint and #Office365 don't actually know about #SP2013 SP1 but Office365 requires #IE9

**Comment by ThorstenHans** [comment]
duplicated see #45

**Comment by manu-khullar** [comment]
Hi Thorsten...I communicated the issue to the person who logged #45 I was not aware that he also went ahead and logged...that.

Thanks

**Comment by manu-khullar** [comment]
Also please the changes you need to make to fix in IE8 :) in my first comment
